### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by borupdaniel** [gpilab/gpi-core-nodes-feedstock#1]
Right now I get the following failure when trying to run a local build from this feedstock:
```(build) 13:38:21 [src] DDB-Mayo: conda build -c conda-forge -c defaults -c danielborup --user danielborup --label main gpi-core-nodes-feedstock/recipe
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /Users/m206107/src/gpi-core-nodes-feedstock/recipe/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /Users/m206107/src/gpi-core-nodes-feedstock/recipe/conda_build_config.yaml
Attempting to finalize metadata for gpi-core-nodes
INFO:conda_build.metadata:Attempting to finalize metadata for gpi-core-nodes
Collecting package metadata: ...working... done                                                                                                                                                        
Solving environment: ...working... done
Collecting package metadata: ...working... done
Solving environment: ...working... done
BUILD START: ['gpi-core-nodes-2.0.0alpha-py37_0.tar.bz2']
Collecting package metadata: ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/m206107/gpi_stack/envs/build/conda-bld/gpi-core-nodes_1562092710752/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla


The following NEW packages will be INSTALLED:

    bzip2:           1.0.6-h1de35cc_1002           conda-forge
    ca-certificates: 2019.6.16-hecc5488_0          conda-forge
    certifi:         2019.6.16-py37_0              conda-forge
    cytoolz:         0.9.0.1-py37h470a237_1        conda-forge
    dbus:            1.13.6-h2f22bb5_0             conda-forge
    eigen:           3.3.7-h04f5b5a_1000           conda-forge
    expat:           2.2.5-h6de7cb9_1003           conda-forge
    fftw:            3.3.8-nompi_h5c49c53_1106     conda-forge
    freetype:        2.10.0-h24853df_0             conda-forge
    gettext:         0.19.8.1-h46ab8bc_1002        conda-forge
    glib:            2.58.3-h9d45998_1001          conda-forge
    gpi:             1.1.1rc2-py37_0               local      
    h5py:            2.9.0-nompi_py37h35dc34b_1102 conda-forge
    hdf5:            1.10.4-nompi_h0cbb7df_1106    conda-forge
    icu:             58.2-h0a44026_1000            conda-forge
    intel-openmp:    2019.4-233                               
    jpeg:            9c-h1de35cc_1001              conda-forge
    libblas:         3.8.0-10_mkl                  conda-forge
    libcblas:        3.8.0-10_mkl                  conda-forge
    libcxx:          8.0.0-4                       conda-forge
    libcxxabi:       8.0.0-4                       conda-forge
    libffi:          3.2.1-h6de7cb9_1006           conda-forge
    libgfortran:     3.0.1-0                       conda-forge
    libiconv:        1.15-h01d97ff_1005            conda-forge
    liblapack:       3.8.0-10_mkl                  conda-forge
    libpng:          1.6.37-h2573ce8_0             conda-forge
    libtiff:         4.0.10-hd08fb8f_1003          conda-forge
    llvm-openmp:     8.0.0-h770b8ee_0              conda-forge
    lz4-c:           1.8.3-h6de7cb9_1001           conda-forge
    mkl:             2019.4-233                               
    ncurses:         6.1-h0a44026_1002             conda-forge
    numpy:           1.11.3-py37hdf140aa_1207      conda-forge
    olefile:         0.46-py_0                     conda-forge
    openssl:         1.1.1b-h01d97ff_2             conda-forge
    pcre:            8.41-h0a44026_1003            conda-forge
    pillow:          6.0.0-py37h7095ceb_0          conda-forge
    pip:             19.1.1-py37_0                 conda-forge
    psutil:          5.6.3-py37h01d97ff_0          conda-forge
    pyopengl:        3.1.3b2-py_1                  conda-forge
    pyqt:            5.9.2-py37h2a560b1_0          conda-forge
    python:          3.7.3-h93065d6_1              conda-forge
    qimage2ndarray:  1.7-py_0                      conda-forge
    qt:              5.9.7-h93ee506_2              conda-forge
    qtpy:            1.8.0-py_0                    conda-forge
    readline:        8.0-hcfe32e1_0                conda-forge
    setuptools:      41.0.1-py37_0                 conda-forge
    sip:             4.19.8-py37h0a44026_1000      conda-forge
    six:             1.12.0-py37_1000              conda-forge
    sqlite:          3.28.0-hb7d70f7_1             conda-forge
    tk:              8.6.9-h2573ce8_1002           conda-forge
    toolz:           0.9.0-py_1                    conda-forge
    wheel:           0.33.4-py37_0                 conda-forge
    xz:              5.2.4-h1de35cc_1001           conda-forge
    zlib:            1.2.11-h1de35cc_1004          conda-forge
    zstd:            1.4.0-ha9f0a20_0              conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting package metadata: ...working... done
Solving environment: ...working... done
Source cache directory is: /Users/m206107/gpi_stack/envs/build/conda-bld/src_cache
INFO:conda_build.source:Source cache directory is: /Users/m206107/gpi_stack/envs/build/conda-bld/src_cache
Found source in cache: v2.0.0alpha_8ea000f75b.tar.gz
INFO:conda_build.source:Found source in cache: v2.0.0alpha_8ea000f75b.tar.gz
Extracting download
source tree in: /Users/m206107/gpi_stack/envs/build/conda-bld/gpi-core-nodes_1562092710752/work
export PREFIX=/Users/m206107/gpi_stack/envs/build/conda-bld/gpi-core-nodes_1562092710752/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
export BUILD_PREFIX=/Users/m206107/gpi_stack/envs/build/conda-bld/gpi-core-nodes_1562092710752/_build_env
export SRC_DIR=/Users/m206107/gpi_stack/envs/build/conda-bld/gpi-core-nodes_1562092710752/work
Traceback (most recent call last):
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/conda/_vendor/toolz/__init__.py", line 28, in <module>
    from cytoolz import __version__ as cytoolz_version
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/cytoolz/__init__.py", line 1, in <module>
    from .itertoolz import *
  File "cytoolz/itertoolz.pyx", line 17, in init cytoolz.itertoolz
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/random.py", line 42, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: cannot import name 'log' from 'math' (/Users/m206107/gpi_stack/envs/build/conda-bld/gpi-core-nodes_1562092710752/work/math/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/conda/cli/main.py", line 137, in main
    from ..activate import main as activator_main
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/conda/activate.py", line 21, in <module>
    from ._vendor.toolz import concatv, drop
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/conda/_vendor/toolz/__init__.py", line 35, in <module>
    from .itertoolz import *
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/conda/_vendor/toolz/itertoolz.py", line 6, in <module>
    from random import Random
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/random.py", line 42, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: cannot import name 'log' from 'math' (/Users/m206107/gpi_stack/envs/build/conda-bld/gpi-core-nodes_1562092710752/work/math/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/conda/_vendor/toolz/__init__.py", line 28, in <module>
    from cytoolz import __version__ as cytoolz_version
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/cytoolz/__init__.py", line 3, in <module>
    from .functoolz import *
  File "cytoolz/functoolz.pyx", line 8, in init cytoolz.functoolz
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/cytoolz/_signatures.py", line 1, in <module>
    from toolz._signatures import *
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/toolz/__init__.py", line 1, in <module>
    from .itertoolz import *
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/toolz/itertoolz.py", line 6, in <module>
    from random import Random
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/random.py", line 42, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: cannot import name 'log' from 'math' (/Users/m206107/gpi_stack/envs/build/conda-bld/gpi-core-nodes_1562092710752/work/math/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/conda/__main__.py", line 8, in <module>
    sys.exit(main())
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/conda/cli/main.py", line 145, in main
    init_loggers()
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/conda/cli/main.py", line 56, in init_loggers
    from ..gateways.logging import initialize_logging, set_verbosity
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/conda/gateways/logging.py", line 14, in <module>
    from ..common.io import attach_stderr_handler
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/conda/common/io.py", line 29, in <module>
    from .path import expand
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/conda/common/path.py", line 16, in <module>
    from .._vendor.toolz import accumulate, concat, take
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/conda/_vendor/toolz/__init__.py", line 35, in <module>
    from .itertoolz import *
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/conda/_vendor/toolz/itertoolz.py", line 6, in <module>
    from random import Random
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/random.py", line 42, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: cannot import name 'log' from 'math' (/Users/m206107/gpi_stack/envs/build/conda-bld/gpi-core-nodes_1562092710752/work/math/__init__.py)

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


Traceback (most recent call last):
  File "/Users/m206107/gpi_stack/envs/build/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 445, in main
    execute(sys.argv[1:])
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 436, in execute
    verify=args.verify, variants=args.variants)
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/conda_build/build.py", line 2299, in build_tree
    notest=notest,
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/conda_build/build.py", line 1445, in build
    cwd=src_dir, stats=build_stats)
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/conda_build/utils.py", line 374, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/Users/m206107/gpi_stack/envs/build/lib/python3.7/site-packages/conda_build/utils.py", line 354, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/Users/m206107/gpi_stack/envs/build/conda-bld/gpi-core-nodes_1562092710752/work/conda_build.sh']' returned non-zero exit status 1.
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# Name                    Version                   Build  Channel
anaconda-client           1.7.2                      py_0    conda-forge
asn1crypto                0.24.0                py37_1003    conda-forge
attrs                     19.1.0                     py_0    conda-forge
beautifulsoup4            4.7.1                 py37_1001    conda-forge
blinker                   1.4                        py_1    conda-forge
bzip2                     1.0.6             h1de35cc_1002    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_0    conda-forge
cffi                      1.12.3           py37hccf1714_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
clyent                    1.2.2                      py_1    conda-forge
conda                     4.6.14                   py37_0    conda-forge
conda-build               3.18.2                   py37_0    conda-forge
conda-forge-pinning       2019.07.01                    0    conda-forge
conda-package-handling    1.3.10                   py37_0    conda-forge
conda-smithy              3.4.0                      py_0    conda-forge
cryptography              2.7              py37h212c5bf_0    conda-forge
curl                      7.64.1               h22ea746_0    conda-forge
cytoolz                   0.9.0.1          py37h470a237_1    conda-forge
decorator                 4.4.0                      py_0    conda-forge
deprecated                1.2.5                      py_0    conda-forge
expat                     2.2.5             h6de7cb9_1003    conda-forge
filelock                  3.0.10                     py_0    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
git                       2.22.0          pl526hbdf3604_0    conda-forge
gitdb2                    2.0.5                      py_0    conda-forge
gitpython                 2.1.11                     py_0    conda-forge
glob2                     0.7                        py_0    conda-forge
icu                       58.2              h0a44026_1000    conda-forge
idna                      2.8                   py37_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isodate                   0.6.0                      py_1    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
jsonschema                3.0.1                    py37_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
krb5                      1.16.3            hcfa6398_1001    conda-forge
libarchive                3.3.3             h5c473cc_1005    conda-forge
libcurl                   7.64.1               h16faf7d_0    conda-forge
libcxx                    8.0.0                         4    conda-forge
libcxxabi                 8.0.0                         4    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
liblief                   0.9.0                h2a1bed3_1    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libxml2                   2.9.9                hd80cff7_0    conda-forge
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
lzo                       2.10              h1de35cc_1000    conda-forge
markupsafe                1.1.1            py37h1de35cc_0    conda-forge
msrest                    0.6.8                      py_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
oauthlib                  3.0.1                      py_0    conda-forge
openssl                   1.1.1b               h01d97ff_2    conda-forge
perl                      5.26.2            haec8ef5_1006    conda-forge
pip                       19.1.1                   py37_0    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
psutil                    5.6.3            py37h01d97ff_0    conda-forge
py-lief                   0.9.0            py37h6d6d4d2_1    conda-forge
pycosat                   0.6.3           py37h1de35cc_1001    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pycrypto                  2.6.1           py37h1de35cc_1002    conda-forge
pygithub                  1.43.6                   py37_0    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyrsistent                0.15.2           py37h01d97ff_0    conda-forge
pysocks                   1.7.0                    py37_0    conda-forge
python                    3.7.3                h0d93f26_0    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-libarchive-c       2.8                   py37_1004    conda-forge
pytz                      2019.1                     py_0    conda-forge
pyyaml                    5.1.1            py37h01d97ff_0    conda-forge
readline                  7.0               hcfe32e1_1001    conda-forge
requests                  2.22.0                   py37_0    conda-forge
requests-oauthlib         1.2.0                      py_0    conda-forge
ruamel                    1.0                      py37_0    conda-forge
ruamel.yaml               0.15.96          py37h01d97ff_0    conda-forge
ruamel_yaml               0.15.71         py37h1de35cc_1000    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
smmap2                    2.0.5                      py_0    conda-forge
soupsieve                 1.9.2                    py37_0    conda-forge
sqlite                    3.28.0               h9721f7c_0    conda-forge
tk                        8.6.9             h2573ce8_1002    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tqdm                      4.32.2                     py_0    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
urllib3                   1.24.3                   py37_0    conda-forge
vsts-python-api           0.1.22                     py_0    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
wrapt                     1.11.2           py37h01d97ff_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
yaml                      0.1.7             h1de35cc_1001    conda-forge
zlib                      1.2.11            h1de35cc_1004    conda-forge
zstd                      1.4.0                ha9f0a20_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : build
    active env location : /Users/m206107/gpi_stack/envs/build
            shell level : 2
       user config file : /Users/m206107/.condarc
 populated config files : /Users/m206107/.condarc
          conda version : 4.7.5
    conda-build version : 3.18.3
         python version : 3.7.1.final.0
       virtual packages : 
       base environment : /Users/m206107/gpi_stack  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/m206107/gpi_stack/pkgs
                          /Users/m206107/.conda/pkgs
       envs directories : /Users/m206107/gpi_stack/envs
                          /Users/m206107/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.5 requests/2.21.0 CPython/3.7.1 Darwin/18.6.0 OSX/10.14.5
                UID:GID : 1851765807:1387956079
             netrc file : None
           offline mode : False
```
</details>

**Comment by borupdaniel** [comment]
@aganders3

**Comment by borupdaniel** [comment]
I'm pretty lost on what the build script is trying to do here. We want to build this as a package, but then have it placed inside gpi/node-libs rather than on its own in site-packages — is there a reason for that? I'm not sure if that setup is going to work with having two packages running on their own CI pipelines in conda forge.

**Comment by aganders3** [comment]
Yeah I think that can change. GPI right now does not look for any node
libraries in site-packages but we could add that as a framework feature. I
think packaging the nodes inside the framework folder is a relic from older
installation methods.

**Comment by borupdaniel** [comment]
I put some OSX packages on my channel. Could you give them a quick test? Rename your .gpirc to hide it, then in a clean environment, run this to install:

```
conda install -c danielborup -c conda-forge gpi-core-nodes
```

then run GPI and see if it works correctly.

**Comment by borupdaniel** [comment]
I just tested and was able to install/run the framework and core nodes into an environment with python 3.6 and qt4 as well. 

I'd like to go ahead and tag the release and then submit the recipe to conda forge. My only question is should this be v2.0 or v1.1? The way the core nodes are now written requires the update to GPI as well, and I'm not familiar enough with semantic versioning to know if that counts as backwards compatible or not.

**Comment by aganders3** [comment]
Thanks - I'll try to test this today or tomorrow as well.

I'm looking at the changes in the core nodes and it seems like some are backward-incompatible. By that I mean new nodes written against the changed API may not work on older versions of GPI. I think this is somewhat rare in that it's only the nodes that define their own custom widgets. It doesn't feel like a giant update, but nonetheless I think that would bump us to 2.0.0.

**Comment by borupdaniel** [comment]
Oh, and we do need some tests as well.
